<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVIl4SwA\SK_ITCBundle_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVIl4SwA/SK_ITCBundle_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVIl4SwA.legacy');

    return;
}

if (!\class_exists(SK_ITCBundle_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVIl4SwA\SK_ITCBundle_KernelDevDebugContainer::class, SK_ITCBundle_KernelDevDebugContainer::class, false);
}

return new \ContainerVIl4SwA\SK_ITCBundle_KernelDevDebugContainer([
    'container.build_hash' => 'VIl4SwA',
    'container.build_id' => 'b5904d5d',
    'container.build_time' => 1576161390,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVIl4SwA');
